kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
  selector:
    app: front